### ISSUE TITLE
Faster sampling window using micropython.

### ISSUE THREAD

**Issue by veebch** [pimoroni/bh1745-python#7]
I'm using the boilerplate code for sampling using micropython (without a breakout garden... sda and scl on gpio 4 and 5 respectively).

    import time
    
    import pimoroni_i2c
    import breakout_bh1745

    PINS_BREAKOUT_GARDEN = {"sda": 4, "scl": 5}

    I2C = pimoroni_i2c.PimoroniI2C(**PINS_BREAKOUT_GARDEN)
    bh1745 = breakout_bh1745.BreakoutBH1745(I2C)

    bh1745.leds(False)

    while True:
        rgbc_raw = bh1745.rgbc_raw()
        print(rgbc_raw[3])

The code happily reads samples at a rate of a few readings a second. 
Is there any way to control the speed of the sampling, eg a 10ms sample?

Thank you

EDIT: Grammar and manners

**Comment by Gadgetoid** [comment]
You can use `bh1745.measurement_time_ms()` to change the measurement time in theory.

There's a ... lot of documentation we still need to do!

**Comment by Gadgetoid** [comment]
Note- the BH1745 library built into our MicroPython is not this Python one, but the written-for-Pico C++ one.

You can find a poor substitute for a function reference here - https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/breakout_bh1745/breakout_bh1745.h#L21-L28

Or just `dir(bh1745)` in the repl.

**Comment by veebch** [comment]
Got it! It looks like the breakout code constrains values to between 0 and 65535

I will have a dig around and the C++ and see what I can figure out.

Thanks!
